src/AppBundle/Form/Type/FormTranslationType.php
<?php

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use \Symfony\Component\Form\FormView;
use \Symfony\Component\Form\FormInterface;
use Symfony\Component\Intl\Intl;
use Symfony\Component\Form\FormBuilderInterface;

class FormTranslationType extends AbstractType {
  private $local;
  private $locales;

  public function __construct($local, $locales) {
    $this->local = $local;
    $this->locales = $locales;
  }
    
  public function setDefaultOptions(OptionsResolverInterface $resolver) {
    foreach($this->locales as $l){
      $lang[$l] = Intl::getLanguageBundle()->getLanguageName($l);  
    }
    $resolver->setDefaults(array(
        'data' => $lang
    ));
  }

  public function getName() {
    return 'formtranslation';
  }

}

src/AppBundle/Resources/views/Form/form_div_layout.html.twig
{% block archivo_widget %}
    {% set irudi = form.parent.vars.attr['data-image']|default(false) %}
    {% set file_name = form.file.vars.data|split('/')|last %}
      {#<pre class="hide hide1">{{ dump(form.vars.form.children) }}</pre>#}
      {#<pre class="hide hide2">{{ dump(form) }}</pre>#}
      {#<pre class="hide hide2">{{ dump(form.children) }}</pre>#}
    {% if form.id.vars.value|default is not empty %}{% set id_principal = form.id.vars.value %}{% else %}{% set id_principal = form.vars.name %}{% endif %}
    {% if irudi %}
      <div class="entity_form_row column archivo_widget" data-id="{{ id_principal }}" data-orden="{{ form.orden.vars.data }}">
        <div class="archivo_opciones">
          <i class="fa fa-trash-o archivo_remove left" title="{{ 'archivo_widget.title_delete'|trans|raw }}"></i>
          <i class="fa fa-file-image-o archivo_edit left" title="{{ 'archivo_widget.title_edit'|trans|raw }}"></i>
          <i class="fa fa-pencil archivo_alt left" title="{{ 'archivo_widget.title_alt'|trans|raw }}" data-url="{{'/archivo/' ~ id_principal ~ '/edit'}}" onclick="appUtil.showModal(this);"></i>
        </div>
        <div class="archivo_loading">
          <i class="fa fa-spinner fa-spin"></i>
        </div>
        <div class="archivo_icon">
          <img class="archivo_thumbnail" src="{{ '/' ~ form.file.vars.data }}" onerror="imgError(this);" title="{{ 'archivo_widget.title_download'|trans|raw }}">
        </div>
        <div class="archivo_link"><a href="{{ '/' ~ form.file.vars.data }}" target="_new" title="{{ file_name }}">{{ file_name }}</a></div>
        <div class="archivo_info">
          <div class="archivo_info_alt"></div>
          <div class="archivo_info_size"><span class="archivo_info_size_resolution"></span><span class="archivo_info_size_weight"></span></div>
        </div>
        {% set idFile = id_principal %}
        {% set id = 'archivo_' ~ id_principal %}
        <input type="file" id="{{ id }}" class="archivo_file" name="archivo[{{ idFile }}]">
        <input name="archivo[{{ id_principal }}][id]" class="archivo_hidden_id" type="hidden" value="{{ id_principal }}" >
        <input name="archivo[{{ id_principal }}][orden]" class="archivo_hidden_orden" type="hidden" value="{{ form.orden.vars.data }}" >
        <input name="archivo[{{ id_principal }}][alt]" class="archivo_hidden_alt" type="hidden" value="{{ form.alt.vars.data }}" >
        <input name="archivo[{{ id_principal }}][file]" class="archivo_hidden_file" type="hidden" value="{{ form.file.vars.data }}" >
      </div>
    {% else %}

      {% set ext = form.file.vars.data|split('.')|last %}
      {% if ext == 'pdf' %}
        {% set fa_icon = 'fa-file-pdf-o' %}
      {% elseif ext == 'xls' or ext == 'xlsx' %}
        {% set fa_icon = 'fa-file-excel-o' %}
      {% elseif ext == 'doc' or ext == 'docx' %}
        {% set fa_icon = 'fa-file-word-o' %}
      {% else %}
        {% set fa_icon = 'fa-file-o' %}
      {% endif %}

      <div class="entity_form_row column archivo_widget" data-id="{{ id_principal }}" data-orden="{{ form.orden.vars.data }}">
        <div class="archivo_opciones">
          <i class="fa fa-trash-o archivo_remove left" title="{{ 'archivo_widget.title_delete'|trans|raw }}"></i>
          <i class="fa fa-file-image-o archivo_edit left" title="{{ 'archivo_widget.title_edit'|trans|raw }}"></i>
        </div>
        <div class="archivo_loading">
          <i class="fa fa-spinner fa-spin"></i>
        </div>
        <div class="archivo_icon">
          <i class="fa {{ fa_icon }}" title="{{ 'archivo_widget.title_download'|trans|raw }}"></i>
        </div>
        <div class="archivo_link"><a href="{{ '/' ~ form.file.vars.data }}" target="_new" title="{{ 'archivo_widget.title_download'|trans|raw }}">{{ file_name }}</a></div>
        <div class="archivo_info">
          <div class="archivo_info_alt"></div>
          <div class="archivo_info_size"><span class="archivo_info_size_resolution"></span><span class="archivo_info_size_weight"></span></div>
        </div>
        {% set idFile = id_principal %}
        {% set id = 'archivo_' ~ id_principal %}
        <input type="file" id="{{ id }}" class="archivo_file" name="archivo[{{ idFile }}]">
        <input name="{{ form.parent.parent.vars.name }}[archivo][{{ id_principal }}][id]" class="archivo_hidden_id" type="hidden" value="{{ id_principal }}" disabled="disabled">
        <input name="{{ form.parent.parent.vars.name }}[archivo][{{ id_principal }}][orden]" class="archivo_hidden_orden" type="hidden" value="{{ form.orden.vars.data }}" disabled="disabled">
        <input name="{{ form.parent.parent.vars.name }}[archivo][{{ id_principal }}][alt]" class="archivo_hidden_alt" type="hidden" value="{{ form.alt.vars.data }}" disabled="disabled">
        <input name="{{ form.parent.parent.vars.name }}[archivo][{{ id_principal }}][file]" class="archivo_hidden_file" type="hidden" value="{{ form.file.vars.data }}" disabled="disabled">
      </div>
    {% endif %}
{% endblock %}

{%- block form_widget_compound -%}
  {% if attr['data-type'] is defined %}
    {% set mota = attr['data-type'] %}
  {% else %}
    {% set mota = 'default' %}
  {% endif %}

  {% if mota == 'Archivo' %}
    {% if attr['data-extensiones'] is defined %}{% set ext = attr['data-extensiones'] %}{% else %}{% set ext = 'archivo_widget.help_all'|trans %}{% endif %}
    {% if attr['data-max_file_size'] is defined %}{% set size = attr['data-max_file_size'] ~ 'MB' %}{% else %}{% set size = 'archivo_widget.help_unlimited'|trans %}{% endif %}
    {% if attr['data-max_file_count'] is defined %}{% set count = attr['data-max_file_count'] %}{% else %}{% set count = 'archivo_widget.help_unlimited'|trans %}{% endif %}
    {% if attr['data-max_resolution'] is defined %}{% set resolution = attr['data-max_resolution'] %}{% else %}{% set resolution = 'archivo_widget.help_unlimited'|trans %}{% endif %}
    {% if attr['data-label'] is defined %}
      <legend class="archivo_lenged">{{ attr['data-label']|default('archivo')|trans }}</legend>
    {% endif %}
      <div class="archivo_help {% if attr['data-label'] is defined %} margin1 {% endif %}">
        <div class="archivo_help_one"><span class="archivo_help_text">{{ 'archivo_widget.help_extension'|trans|raw }}</span><span class="archivo_help_info">{{ ext }}</span></div>
        <div class="archivo_help_one"><span class="archivo_help_text">{{ 'archivo_widget.help_size'|trans|raw }}</span><span class="archivo_help_info">{{ size }}</span></div>
        <div class="archivo_help_one"><span class="archivo_help_text">{{ 'archivo_widget.help_count'|trans|raw }}</span><span class="archivo_help_info">{{ count }}</span></div>
        <div class="archivo_help_one"><span class="archivo_help_text">{{ 'archivo_widget.help_resolution'|trans|raw }}</span><span class="archivo_help_info">{{ resolution }}</span></div>
      </div>
      <a class="add_archivo">
        <i class="fa fa-plus" title='{{ "archivo_widget.title_new"|trans|raw }}'></i>
      </a>
      <input class="hide new_archivo" id="new_archivo" name="new_archivo" type="file">
      <div {{ block('widget_container_attributes') }} class="archivo_content">
          {%- if form.parent is empty -%}
              {{ form_errors(form) }}
          {%- endif -%}
          {{ block('form_rows') }}
          {{- form_rest(form) -}}
      </div>
      <ul class="hide archivo_translate_collection">
        <li class="archivo_translate error_extension">{{ 'archivo_widget.error_extension'|trans|raw }}</li>
        <li class="archivo_translate error_resolution">{{ 'archivo_widget.error_resolution'|trans|raw }}</li>
        <li class="archivo_translate error_size">{{ 'archivo_widget.error_size'|trans|raw }}</li>
        <li class="archivo_translate error_count">{{ 'archivo_widget.error_count'|trans|raw }}</li>
        <li class="archivo_translate error_generate_file">{{ 'archivo_widget.error_generate_file'|trans|raw }}</li>
        <li class="archivo_translate error_code_0">{{ 'archivo_widget.error_code_0'|trans|raw }}</li>
        <li class="archivo_translate error_code_1">{{ 'archivo_widget.error_code_1'|trans|raw }}</li>
        <li class="archivo_translate error_code_2">{{ 'archivo_widget.error_code_2'|trans|raw }}</li>
        <li class="archivo_translate delete_confirm">{{ 'archivo_widget.delete_confirm'|trans|raw }}</li>
        <li class="archivo_translate title_edit">{{ 'archivo_widget.title_edit'|trans|raw }}</li>
        <li class="archivo_translate title_delete">{{ 'archivo_widget.title_delete'|trans|raw }}</li>
        <li class="archivo_translate title_download">{{ 'archivo_widget.title_download'|trans|raw }}</li>
        <li class="archivo_translate title_new">{{ 'archivo_widget.title_new'|trans|raw }}</li>
        <li class="archivo_translate help_extension">{{ 'archivo_widget.help_extension'|trans|raw }}</li>
        <li class="archivo_translate help_resolution">{{ 'archivo_widget.help_resolution'|trans|raw }}</li>
        <li class="archivo_translate help_size">{{ 'archivo_widget.help_size'|trans|raw }}</li>
        <li class="archivo_translate help_count">{{ 'archivo_widget.help_count'|trans|raw }}</li>
      </ul>
  {% else %}
      <div {{ block('widget_container_attributes') }}>
          {%- if form.parent is empty -%}
              {{ form_errors(form) }}
          {%- endif -%}
          {{- block('form_rows') -}}
          {{- form_rest(form) -}}
      </div>
  {% endif  %}
{%- endblock form_widget_compound -%}

{% block form_row -%}

    {% if form.parent.vars.attr['data-type'] is defined %}
      {% set mota = form.parent.vars.attr['data-type'] %}
    {% else %}
      {% set mota = 'default' %}
    {% endif %}

    {% if mota == 'Archivo' %}
      {{ block('archivo_widget') }}
    {% else %}
      <div class="row">
        <div class="small-12 columns error">
          {{- form_errors(form) -}}
        </div>
        {% if form.vars.name == 'translations' %}
          <div class="small-12 columns">
            {{- form_widget(form) -}}
          </div>
        {% else %}
          <div class="small-12 columns">
            {{- form_label(form) -}}
          </div>

          <div class="small-12 columns">
            {{- form_widget(form) -}}
          </div>
        {% endif %}
      </div>
    {% endif %}
{%- endblock form_row %}

{%- block form_label -%}
    {% if label is not sameas(false) %}
        {%- if not compound -%}
            {% set label_attr = label_attr|merge({'for': id}) %}
        {%- endif -%}
        {%- if required -%}
            {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
        {%- endif -%}
        {%- if label is empty -%}
            {% set label = name|humanize %}
        {%- endif -%}
        <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>
          {%- if required -%}
            <a class="entity_form_info" title="{{ 'Este campo es obligatorio' | trans }}"><i class="fa fa-info-circle"></i></a>
          {%- endif -%}
          {{ label|trans({}, translation_domain) | raw }}
        </label>
    {%- endif -%}
{%- endblock form_label -%}

{% block datetime_widget -%}
    {% if widget == 'single_text' %}
        {{- block('form_widget_simple') -}}
    {% else -%}
        <div {{ block('widget_container_attributes') }}>
            {{- form_errors(form.date) -}}
            {{- form_errors(form.time) -}}
          <div class="inline">
            {{- form_widget(form.date) -}}
          </div>
          <div class="inline">
            {{- form_widget(form.time) -}}
          </div>
        </div>
    {%- endif %}
{%- endblock datetime_widget %}

{% block date_widget -%}
    {% if widget == 'single_text' -%}
        {{ block('form_widget_simple') }}
    {%- else -%}
        <div {{ block('widget_container_attributes') }} class="rowFormDateTime">
            {{- date_pattern|replace({
                '{{ year }}':  form_widget(form.year),
                '{{ month }}': form_widget(form.month),
                '{{ day }}':   form_widget(form.day),
            })|raw -}}
        </div>
    {%- endif %}
{%- endblock date_widget %}

{% block time_widget -%}
    {% if widget == 'single_text' -%}
        {{ block('form_widget_simple') }}
    {%- else -%}
        {% set vars = widget == 'text' ? { 'attr': { 'size': 1 }} : {} -%}
        <div {{ block('widget_container_attributes') }} class="rowFormDateTime">
            {{ form_widget(form.hour, vars) }}{% if with_minutes %}:{{ form_widget(form.minute, vars) }}{% endif %}{% if with_seconds %}:{{ form_widget(form.second, vars) }}{% endif %}
        </div>
    {%- endif %}
{%- endblock time_widget %}

{% block entity_widget -%}
  {% if attr['ajax'] | default is not empty %}
    {% set values = {} %}
    {% set defaultValue = '' %}
    {% if data | default is not empty %}
      {% set defaultValue = data.id %}
      {% set values = values|merge({ defaultValue: data }) %}
    {% endif %}
    <select name='{{ full_name }}' id='{{ id }}' {{ attr | select2ajax }}>
      <option value=''>{{ 'select.all' | trans }}</option>
      {% if group_by is defined %}
        {% for key, choices in choices %}
          <optgroup label="{{ key |trans }}">
            {% for choice in choices %}
              <option value='{{ choice.id }}' {{ defaultValue is sameas(choice.id) ? 'selected' : '' }}>{{ choice }}</option>
            {% endfor %}
          </optgroup>
        {% endfor %}
      {% else %}
        {% for choice in values %}
          <option value='{{ choice.id }}' {{ defaultValue is sameas(choice.id) ? 'selected' : '' }}>{{ choice }}</option>
        {% endfor %}
      {% endif %}
    </select>
  {% else %}
    {{ form_widget(form) }}
  {% endif %}
{%- endblock entity_widget %}

{%- block button_row -%}
    <div class="form_button_row">
        {{- form_widget(form) -}}
    </div>
{%- endblock button_row -%}

src/AppBundle/Resources/views/Form/form_div_layout_submit.html.twig
{% block form_row -%}
    <div class="row">
      <div class="small-12 columns error">
        {{- form_errors(form) -}}
      </div>
      {% if form.vars.name == 'translations' %}
        <div class="small-12 columns">
          {{- form_widget(form) -}}
        </div>
      {% else %}
        <div class="small-3 columns">
          {{- form_label(form) -}}
        </div>

        <div class="small-9 columns">
          {{- form_widget(form) -}}
        </div>
      {% endif %}
      
    </div>
{%- endblock form_row %}

{%- block form_label -%}
    {% if label is not sameas(false) %}
        {%- if not compound -%}
            {% set label_attr = label_attr|merge({'for': id}) %}
        {%- endif -%}
        {%- if required -%}
            {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
        {%- endif -%}
        {%- if label is empty -%}
            {% set label = name|humanize %}
        {%- endif -%}
        <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>
          {%- if required -%}
            <a class="entity_form_info" title="{{ 'Este campo es obligatorio' | trans }}"><i class="fa fa-info-circle"></i></a>
          {%- endif -%}
          {{ label|trans({}, translation_domain) | raw }}
        </label>
    {%- endif -%}
{%- endblock form_label -%}

{% block datetime_widget -%}
    {% if widget == 'single_text' %}
        {{- block('form_widget_simple') -}}
    {% else -%}
        <div {{ block('widget_container_attributes') }}>
            {{- form_errors(form.date) -}}
            {{- form_errors(form.time) -}}
          <div class="inline">
            {{- form_widget(form.date) -}}
          </div>
          <div class="inline">
            {{- form_widget(form.time) -}}
          </div>
        </div>
    {%- endif %}
{%- endblock datetime_widget %}

{% block date_widget -%}
    {% if widget == 'single_text' -%}
        {{ block('form_widget_simple') }}
    {%- else -%}
        <div {{ block('widget_container_attributes') }} class="rowFormDateTime">
            {{- date_pattern|replace({
                '{{ year }}':  form_widget(form.year),
                '{{ month }}': form_widget(form.month),
                '{{ day }}':   form_widget(form.day),
            })|raw -}}
        </div>
    {%- endif %}
{%- endblock date_widget %}

{% block time_widget -%}
    {% if widget == 'single_text' -%}
        {{ block('form_widget_simple') }}
    {%- else -%}
        {% set vars = widget == 'text' ? { 'attr': { 'size': 1 }} : {} -%}
        <div {{ block('widget_container_attributes') }} class="rowFormDateTime">
            {{ form_widget(form.hour, vars) }}{% if with_minutes %}:{{ form_widget(form.minute, vars) }}{% endif %}{% if with_seconds %}:{{ form_widget(form.second, vars) }}{% endif %}
        </div>
    {%- endif %}
{%- endblock time_widget %}

{% block entity_widget -%}
  {% if attr['ajax'] | default is not empty %}
    {% set values = {} %}
    {% set defaultValue = '' %}
    {% if data | default is not empty %}
      {% set defaultValue = data.id %}
      {% set values = values|merge({ defaultValue: data }) %}
    {% endif %}
    <select name='{{ full_name }}' id='{{ id }}' {{ attr | select2ajax }}>
      <option value=''>{{ 'select.all' | trans }}</option>
      {% if group_by is defined %}
        {% for key, choices in choices %}
          <optgroup label="{{ key |trans }}">
            {% for choice in choices %}
              <option value='{{ choice.id }}' {{ defaultValue is sameas(choice.id) ? 'selected' : '' }}>{{ choice }}</option>
            {% endfor %}
          </optgroup>
        {% endfor %}
      {% else %}
        {% for choice in values %}
          <option value='{{ choice.id }}' {{ defaultValue is sameas(choice.id) ? 'selected' : '' }}>{{ choice }}</option>
        {% endfor %}
      {% endif %}
    </select>
  {% else %}
    {{ form_widget(form) }}
  {% endif %}
{%- endblock entity_widget %}

{%- block button_row -%}
    <div class="form_button_row">
        {{- form_widget(form) -}}
    </div>
{%- endblock button_row -%}
{%- block button_widget -%}
    {%- if label is empty -%}
        {%- if label_format is not empty -%}
            {% set label = label_format|replace({
                '%name%': name,
                '%id%': id,
            }) %}
        {%- else -%}
            {% set label = name|humanize %}
        {%- endif -%}
    {%- endif -%}
    <button type="{{ type|default('button') }}" {{ block('button_attributes') }}><i class="fa fa-envelope-o"></i>{{ translation_domain is same as(false) ? label : label|trans({}, translation_domain) }}</button>
{%- endblock button_widget -%}

{%- block submit_widget -%}
    {%- set type = type|default('submit') -%}
    {{ block('button_widget') }}
{%- endblock submit_widget -%}