src/CommonBundle/UserBundle/Entity/User.php
<?php

namespace CommonBundle\UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use CommonBundle\AdministratorBundle\Entity\Menu;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;
use AppBundle\Util\Util;

/**
 * @ORM\Entity
 * @ORM\Table(name="SFAPP_fos_user")
 * @ORM\Entity(repositoryClass="CommonBundle\UserBundle\Entity\UserRepository")
 */
class User extends BaseUser {

  /**
   * @ORM\Id
   * @ORM\Column(type="integer")
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  protected $id;

  /**
   * @ORM\Column(type="string", nullable=true)
   * 
   */
  protected $nombre;

  /**
   * @ORM\Column(type="string", nullable=true)
   */
  protected $apellidos;

  /**
   * @ORM\Column(type="string")
   * 
   */
  protected $username;

  /**
   * @ORM\Column(type="string")
   */
  protected $usernameCanonical;

  /**
   * @ORM\Column(type="string")
   * 
   */
  protected $email;

  /**
   * @ORM\Column(type="string")
   */
  protected $emailCanonical;

  /**
   * @ORM\Column(type="boolean")
   */
  protected $enabled;

  /**
   * The salt to use for hashing
   *
   * @ORM\Column(type="string")
   */
  protected $salt;

  /**
   * Encrypted password. Must be persisted.
   *
   * @ORM\Column(type="string")
   */
  protected $password;

  /**
   * Plain password. Used for model validation. Must not be persisted.
   *
   * @ORM\Column(type="string", nullable=true)
   */
  protected $plainPassword;

  /**
   * @ORM\Column(type="datetime", nullable=true)
   */
  protected $lastLogin;

  /**
   * Random string sent to the user email address in order to verify it
   *
   * @ORM\Column(type="string", nullable=true)
   */
  protected $confirmationToken;

  /**
   * @ORM\Column(type="datetime", nullable=true)
   */
  protected $passwordRequestedAt;

  /**
   * @ORM\Column(type="boolean")
   */
  protected $locked;

  /**
   * @ORM\Column(type="boolean")
   */
  protected $expired;

  /**
   * @ORM\Column(type="datetime", nullable=true)
   */
  protected $expiresAt;

  /**
   * @ORM\Column(type="array")
   */
  protected $roles;

  /**
   * @ORM\Column(type="boolean")
   */
  protected $credentialsExpired;

  /**
   * @ORM\Column(type="datetime", nullable=true)
   */
  protected $credentialsExpireAt;

  /**
   *    
   * @ORM\Column(type="string", nullable=true)
   */
  protected $locale;

  /**
   * @ORM\ManyToMany(targetEntity="CommonBundle\UserBundle\Entity\Group")
   * @ORM\JoinTable(name="SFAPP_fos_user_user_group",
   *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
   *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
   * )
   */
  protected $groups;

  /**
   * @ORM\ManyToMany(targetEntity="CommonBundle\AdministratorBundle\Entity\Menu", inversedBy="users", cascade={"persist", "remove" })
   * @ORM\JoinTable(name="SFAPP_menu_usuario")
   * */
  protected $menus;

  /**
   * @ORM\Column(name="clave_caducada", type="boolean", nullable=true)
   */
  private $claveCaducada;

  /**
   * @ORM\Column(name="fecha_caducidad_clave", type="date", nullable=true)
   */
  private $fechaCaducidadClave;

  /**
   * @ORM\Column(name="session_id", type="string", length=255, nullable=true)
   */
  private $sessionId;

  /**
   * @ORM\Column(name="logout_auto", type="boolean", nullable=true)
   */
  private $logoutAuto;

  public function __construct() {
    parent::__construct();
  }

  public function __toString() {
    $nombre = '';

    if ($this->getId()) {
      $nombre = $this->nombre . ' ' . $this->apellidos . ' (' . $this->username . ')';
    }

    return $nombre;
  }
  
  public function getNombre() {
    return $this->nombre;
  }

  public function setNombre($nombre) {
    $this->nombre = $nombre;
    return $this;
  }

  public function getApellidos() {
    return $this->apellidos;
  }

  public function setApellidos($apellidos) {
    $this->apellidos = $apellidos;
    return $this;
  }

  public function setLastLogin(\DateTime $time) {
    parent::setLastLogin($time);
  }

  public function getLocale() {
    return $this->locale;
  }

  public function setLocale($locale) {
    $this->locale = $locale;
    return $this;
  }

  public function addMenu(\CommonBundle\AdministratorBundle\Entity\Menu $menus) {
    $menus->addUser($this); 
    $this->menus[] = $menus;

    return $this;
  }

  public function removeMenu(\CommonBundle\AdministratorBundle\Entity\Menu $menus) {
    $this->menus->removeElement($menus);
  }

  public function getMenus() {
    return $this->menus;
  }

  public function getMenuIds() {
    $ids = array();

    foreach ($this->getMenus() as $menu) {
      $ids[] = $menu->getId();
    }

    return $ids;
  }

  public function checkAccess($_controller, $em){
    $info = \AppBundle\Util\Util::getControllerInfo($_controller);
    
    $menu = $em->getRepository('CommonBundleAdministratorBundle:Menu')->comprobarMenu($info['bundle'], $info['controller'], $info['action']);
	
    if($menu){
      return in_array($menu->getId(), $this->getMenuIds());
    }else{
      return true;
    }
  }
  
  public function setPassword($password) {
    if($password) {
      parent::setPassword($password);
    }
  }
  
  public function getEnabled(){
    return $this->enabled;
  }

  public function getTipo(){
    $tipo = '';

    if(in_array('ROLE_ADMIN', $this->roles)){
      $tipo = 'ROLE_ADMIN';
    } else {
	  $notFirst = false;
	  foreach($this->roles as $rol) {
		if ($notFirst) $tipo .= ' ';
		$tipo .= $rol;
		$notFirst = true;
	  }
	}

    return $tipo;
  }

  public function setTipo($tipo = ''){
    if($tipo){
      //$this->addRole(array($tipo));
	  $this->setRoles(array($tipo));
    }else{
      $this->setRoles(array());
    }    
  }

  public function getLocked(){
    return $this->locked;
  }

  public function getExpired(){
    return $this->expired;
  }

  public function getClaveCaducada(){
    return $this->claveCaducada;
  }

  public function setClaveCaducada($claveCaducada = false){
    $this->claveCaducada = $claveCaducada;
  }

  public function getLogoutAuto(){
    return $this->logoutAuto;
  }

  public function setLogoutAuto($logoutAuto = false){
    $this->logoutAuto = $logoutAuto;
  }

  /**
   * Set fecha
   *
   * @param \DateTime $fecha
   * @return Accion
   */
  public function setFechaCaducidadClave($fechaCaducidadClave) {
    $this->fechaCaducidadClave = $fechaCaducidadClave;

    return $this;
  }

  /**
   * Get fecha
   *
   * @return \DateTime 
   */
  public function getFechaCaducidadClave() {
    return $this->fechaCaducidadClave;
  }

  public function setSessionId($sessionId = null) {
    $this->sessionId = $sessionId;

    return $this;
  }

  public function getSessionId() {
    return $this->sessionId;
  }

  public function isAdmin(){
    return Util::semaphore($this->getTipo() === 'ROLE_ADMIN');
  }

  public function renderTipo($params){
	$rol = $params['em']->getRepository('CommonBundleUserBundle:Role')->findOneByMachinename($this->getTipo());
	
	if ($rol) return $rol->getName();
	else return false;
  }
}

src/CommonBundle/UserBundle/Controller/DefaultController.php
<?php

namespace CommonBundle\UserBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use CommonBundle\UserBundle\Entity\User;
use CommonBundle\UserBundle\Form\UserType;
use AppBundle\Util\Util;
use AppBundle\Controller\DefaultController as AppController;

class DefaultController extends AppController {

  public function indexAction(Request $request, $class = 'User') {
    return parent::indexAction($request, $class);
  }

  public function noPermissionsAction() {
    return $this->render('CommonBundleUserBundle:Default:noPermissions.html.twig');
  }

  public function changeLanguageAction($lang) {
    $user = $this->getUser();
    $request = $this->getRequest();
    $userManager = $this->container->get('fos_user.user_manager');

    $this->get('session')->set('_locale', $lang);

    $user->setLocale($lang);
    $userManager->updateUser($user);

    //Cambio o creo cookie
    $cookie_name = $this->container->getParameter('cookie_lang');
    $cookie_lang = $request->cookies->get($cookie_name);    
    //Creo cookie
    $cookie_lang = new Cookie($cookie_name, $lang, 2147483647);
    
    $redirect = new RedirectResponse($request->headers->get('referer'));  
    $redirect->headers->setCookie($cookie_lang);
    return $redirect;
  }

  /**
   * Creates a new User entity.
   *
   */
  public function createAction(Request $request) {
    $form = $this->container->get('fos_user.registration.form');
    $formHandler = $this->container->get('fos_user.registration.form.handler');
    $process = $formHandler->process(false);
    $valid = 0;

    if ($process) {
      $user = $form->getData();
      $valid = 1;
      //return $this->redirect($this->generateUrl('common_bundle_user_show', array('id' => $user->getId())));
    }

    return $this->render('CommonBundleUserBundle:Default:new.html.twig', array(
                'form' => $form->createView(),
                'valid' => $valid,
                'entity' => $user
    ));
  }

  /**
   * Displays a form to create a new User entity.
   *
   */
  public function newAction(Request $request, $class = 'User') {
    return parent::newAction($request, $class);
  }

  /**
   * Finds and displays a User entity.
   *
   */
  public function showAction($id, Request $request, $class = 'User') {
    $em = $this->getDoctrine()->getManager();

    $entity = $em->getRepository('CommonBundleUserBundle:User')->find($id);

    if (!$entity) {
      throw $this->createNotFoundException('Unable to find User entity.');
    }


    return $this->render('CommonBundleUserBundle:Default:show.html.twig', array(
                'entity' => $entity
    ));
  }

  /**
   * Displays a form to edit an existing User entity.
   *
   */
  public function editAction($id, Request $request, $class = 'User') {
    return parent::editAction($id, $request, $class);
  }

  /**
   * Creates a form to edit a User entity.
   *
   * @param User $entity The entity
   *
   * @return \Symfony\Component\Form\Form The form
   */
  private function createEditForm1(User $entity) {
    
    $em = $this->getDoctrine()->getManager();
    $form = $this->createForm(new UserType($em), $entity);

    return $form;
  }

  /**
   * Edits an existing User entity.
   *
   */
  public function updateAction(Request $request, $id) {
    $em = $this->getDoctrine()->getManager();

    $entity = $em->getRepository('CommonBundleUserBundle:User')->find($id);

    if (!$entity) {
      throw $this->createNotFoundException('Unable to find User entity.');
    }

    $editForm = $this->createEditForm1($entity);
    $editForm->handleRequest($request);

    $valid = 0;
    if ($editForm->isValid()) {
      $values = $request->request->get('commonbundle_userbundle_user');
      if (trim($values['password'])) {
        $entity->setPlainPassword($values['password']);
      }
      $em->flush();

      $valid = 1;
    }

    return $this->render('CommonBundleUserBundle:Default:edit.html.twig', array(
                'entity' => $entity,
                'edit_form' => $editForm->createView(),
                'valid' => $valid,
    ));
  }

  /**
   * Deletes a User entity.
   *
   */
  public function deleteAction($id, Request $request, $class = 'User') {
    return parent::deleteAction($id, $request, $class);
  }

  public function enableAction($id) {
    $em = $this->getDoctrine()->getManager();
    $entity = $em->getRepository('CommonBundleUserBundle:User')->find($id);

    if (!$entity) {
      $resp = array('error' => $this->get('translator')->trans('element_not_finded'));
    } else {
      $entity->setEnabled(!$entity->isEnabled());
      $em->flush();

      $resp = array('enabled' => $entity->isEnabled());
    }

    return new Response(json_encode($resp));
  }

  public function permissionsAction() {
    $em = $this->getDoctrine()->getManager();
    $menus = Util::renderTree($em->getRepository('CommonBundleAdministratorBundle:Menu')->getMenuTree(), 0, null, false);
    $users = $em->getRepository('CommonBundleUserBundle:User')->findAll();
    $result = array();
    foreach ($users as $user) {
      $role = $user->getTipo();
      $role = explode(' ',$role);
      if(in_array("ROLE_ADMIN", $role) || in_array("ROLE_PUBLIC_COMPANY", $role))
      {
        $result[] = $user;
      }
    }
    $users = $result;
    return $this->render('CommonBundleUserBundle:Default:permissions.html.twig', array(
                'menus' => $menus,
                'users' => $users
    ));
  }

  public function editPermissionAction($user_id, $menu_id) {
    $resp = array();
    $em = $this->getDoctrine()->getManager();
    $enable = $this->getRequest()->get('enable', false);
    $user = $em->getRepository('CommonBundleUserBundle:User')->find($user_id);
    $menu = $em->getRepository('CommonBundleAdministratorBundle:Menu')->find($menu_id);

    if (!$user || !$menu) {
      $resp = array('error' => $this->get('translator')->trans('element_not_finded'));
    } else {
      $menus = $user->getMenuIds();
      if (!filter_var($enable, FILTER_VALIDATE_BOOLEAN) && !in_array($menu_id, $menus)) {
        $user->addMenu($menu);
        $em->flush();
      }
      if (filter_var($enable, FILTER_VALIDATE_BOOLEAN) && in_array($menu_id, $menus)) {
        $user->removeMenu($menu);
        $em->flush();
      }
    }

    return new Response(json_encode($resp));
  }

  public function resetClaveAction($id){
    $em = $this->getDoctrine()->getManager();
    $userManager = $this->container->get('fos_user.user_manager');
    $user = $em->getRepository('CommonBundleUserBundle:User')->find($id);

    $clave = Util::generatePassword();
    $user->setPlainPassword($clave);
    $user->setClaveCaducada(true);
    $userManager->updateUser($user);

    return $this->render('CommonBundleUserBundle:Default:resetClave.html.twig', array(
                'clave' => $clave,
                'cabecera' => $em->getRepository('CommonBundleUserBundle:User')->getHeadData($user, $this->getRequest()->getLocale(), $this->get('router'), $this->get('translator'))
    ));
  } 

}

src/CommonBundle/UserBundle/Resources/views/Default/edit.html.twig
{% extends '::edit.html.twig' %}

src/CommonBundle/UserBundle/Resources/views/Default/index.html.twig
{% extends '::index.html.twig' %}

{% block titulo_cabecera %}
    <h1>{{ 'Usuarios'|trans }}</h1>
{% endblock %}

src/CommonBundle/UserBundle/Resources/views/Default/new.html.twig
{% extends '::new.html.twig' %}

src/CommonBundle/UserBundle/Resources/views/Default/noAccessPermissions.html.twig
{% extends "base.html.twig" %}

{% block container %}
  <div class="row text-center">
    <h2>{{ 'permission.access.page'|trans }}: <strong>{{ path }}</strong></h2>
  </div>
{% endblock %}

src/CommonBundle/UserBundle/Resources/views/Default/noPermissions.html.twig
{% extends "base.html.twig" %}

{% block container %}
  <div class="row text-center">
    <h2>{{ 'permission.access.page'|trans }}</h2>
  </div>
{% endblock %}

src/CommonBundle/UserBundle/Resources/views/Default/permissions.html.twig
{% extends '::base.html.twig' %}

{% block container %}
  <h1>{{ 'Permisos'|trans }}</h1>

  <table id="tablaContenido_Permisos" class="records_list large-12">
    <thead>
      <tr>
        <th></th>
          {% for user in users %}
          <th>{{ user.username }}</th>
          {% endfor %}
      </tr>
    </thead>
    <tbody>
      {% for menu in menus %}
        <tr>
          <th>
            {{ menu.nombre | raw }}
          </th>
          {% for user in users %}
            <td>
              {% if user.hasRole('ROLE_ADMIN') %}
                {{ true | semaphore }}
              {% else %}
                {% if not menu.admin %}
                  <a href="javascript:activarDesactivarPermiso('{{ path('common_bundle_user_edit_permission', {'user_id' : user.id, 'menu_id' : menu.id }) }}', '{{ menu.id ~ '_' ~ user.id }}');" id="{{ menu.id ~ '_' ~ user.id }}">
                    {{ (menu.id in user.getMenuIds()) | semaphore }}
                  </a>
                {% else %}
                  {{ false | semaphore }}
                {% endif %}
              {% endif %}
            </td>
          {% endfor %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block scripts %}
  <script>
    function activarDesactivarPermiso(url, id) {
      var obj = $('#' + id + ' img');
      var enable = (obj.attr('src').indexOf('green.png') != -1);

      $.ajax({
        url: url,
        data: { enable: enable },
        dataType: 'json',
        success: function (data) {
          if (data.hasOwnProperty('error')) {
            alert(data.error);
          } else {
            if (!enable) {
              obj.attr('src', '/images/green.png');
            } else {
              obj.attr('src', '/images/red.png');
            }
          }
        },
        error: function (jqXHR, ajaxSettings, thrownError) {
          appUtil.errorAjax(jqXHR, ajaxSettings, thrownError);
        }
      });
    }
  </script>
{% endblock %}

src/CommonBundle/UserBundle/Resources/views/Default/resetClave.html.twig
{% extends '::modal.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
{% endblock %}

{% block javascripts %}
  {{ parent() }}
{% endblock %}

{% block container %}
  <ul class="tabs" data-tab>
    <li class="tab-title active"><a href="#tab_home">{{ 'Resetear clave' | trans }}</a></li>
  </ul>

  <div class="tabs-content">
    <div class="content active text-center" id="tab_home">
     <p>Se ha reseteado la clave del usuario, para que el usuario pueda volver a acceder a la aplicación se le debe comunicar la nueva clave:</p>
     <p><b>{{ clave }}</b></p>
    </div>
  </div>
{% endblock %}

src/CommonBundle/UserBundle/Resources/views/Default/show.html.twig
{% extends '::modal.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
{% endblock %}

{% block javascripts %}
  {{ parent() }}
{% endblock %}

{% block container %}
  <h1>{{ 'User'|trans }}</h1>

  <table class="record_properties large-12">
    <tbody>
      <tr>
        <th>{{ 'Username'|trans }}</th>
        <td>{{ entity.username }}</td>
      </tr>
      <tr>
        <th>{{ 'Email'|trans }}</th>
        <td>{{ entity.email }}</td>
      </tr>
      <tr>
        <th>{{ 'Enabled'|trans }}</th>
        <td>{{ entity.enabled|semaphore }}</td>
      </tr>
      <tr>
        <th>{{ 'Lastlogin'|trans }}</th>
        <td>{% if entity.lastLogin %}{{ entity.lastLogin|localizeddate('medium', 'short', app.request.locale) }}{% endif %}</td>
      </tr>
      <tr>
        <th>{{ 'Locale'|trans }}</th>
        <td>{{ entity.locale|lang }}</td>
      </tr>
    </tbody>
  </table>
{% endblock %}